dataset:
  name: ocean_das
  pair_id: [1]
model:
  POD_modes: 5
  alpha: 0.055
  differentiation_method: finite_difference
  differentiation_method_order: 3
  feature_library: polynomial
  feature_library_order: 2
  name: SINDy
  optimizer: STLSQ
  threshold: 10
