dataset:
  name: ocean_das
  pair_id: [6]
model:
  POD_modes: 2
  alpha: 10.0
  differentiation_method: finite_difference
  differentiation_method_order: 2
  feature_library: mixes
  feature_library_order: 1
  name: SINDy
  optimizer: FROLS
  threshold: 50.0