dataset:
  name: ocean_das
  pair_id: [5]
model:
  POD_modes: 10
  alpha: 0.05
  differentiation_method: finite_difference
  differentiation_method_order: 2
  feature_library: polynomial
  feature_library_order: 1
  name: SINDy
  optimizer: STLSQ
  threshold: 10