dataset:
  name: ocean_das
  pair_id: [9]
model:
  POD_modes: 7
  alpha: 0.5
  differentiation_method: finite_difference
  differentiation_method_order: 1
  feature_library: polynomial
  feature_library_order: 1
  name: SINDy
  optimizer: STLSQ
  threshold: 20