dataset:
  name: ocean_das
  pair_id: [2]
model:
  POD_modes: 6
  alpha: 11.0
  differentiation_method: finite_difference
  differentiation_method_order: 5
  feature_library: polynomial
  feature_library_order: 1
  name: SINDy
  optimizer: FROLS
  threshold: 76.0